version: 1.0.{build}

branches:
  only:
    - master

environment:
  GITHUB_TOKEN:
    secure: 9i6jrWpBi99QC1gYYQYMGIxyueGdDuTrbxKIkdwJJGjvv8nhiQeGk4V7lb1Wy6C4
  GITHUB_EMAIL:
    secure: 9KuPMPaDBiLnWjbCSsubN+MFp4a9LOyqPzWcN3zTecQ=

build: off

test: off

deploy_script:
- cmd: appveyor-to-gh-pages-branch.cmd
