version: 1.0.{build}

branches:
  only:
    - master

environment:
  GITHUB_TOKEN:
    secure: 9i6jrWpBi99QC1gYYQYMGIxyueGdDuTrbxKIkdwJJGjvv8nhiQeGk4V7lb1Wy6C4
  GITHUB_EMAIL:
    secure: 9KuPMPaDBiLnWjbCSsubN+MFp4a9LOyqPzWcN3zTecQ=
  SDK_REPO: flex-sdk
  SDK_TARGET: 4.15.0-AIR-22-minimal-Windows

install:
#  - ps: echo "install - $env:SDK_TARGET"
#  - ps: echo "install`: $env:SDK_TARGET"
#  - ps: echo 'install:' $env:SDK_TARGET
#  - cmd: echo 'install:' %SDK_TARGET%
#  - cmd: echo APPVEYOR_BUILD_FOLDER - %APPVEYOR_BUILD_FOLDER%
#  - ps: echo "APPVEYOR_BUILD_FOLDER - $env:APPVEYOR_BUILD_FOLDER"
  - ps: wget https://github.com/mojoco/flex-sdk/archive/4.15.0-AIR-22-minimal-Windows.zip -O $env:APPVEYOR_BUILD_FOLDER\4.15.0-AIR-22-minimal-Windows.zip

cache:
  # invalidate whenever appveyor.yml is changed !
#  - '%APPVEYOR_BUILD_FOLDER%\flex-sdk' -> appveyor.yml
  - '%APPVEYOR_BUILD_FOLDER%\4.15.0-AIR-22-minimal-Windows.zip' -> appveyor.yml

before_build:
  - ps: ls $env:APPVEYOR_BUILD_FOLDER
  - cmd: unzip %APPVEYOR_BUILD_FOLDER%\4.15.0-AIR-22-minimal-Windows.zip
  - ps: ls $env:APPVEYOR_BUILD_FOLDER
  - cmd: rename "%APPVEYOR_BUILD_FOLDER%\flex-sdk-4.15.0-AIR-22-minimal-Windows" "flex-sdk"
  - ps: ls $env:APPVEYOR_BUILD_FOLDER

  - cmd: set FLEX_HOME=%APPVEYOR_BUILD_FOLDER%\flex-sdk
  - cmd: set PATH=%PATH%;%FLEX_HOME%\bin

  - ps: ls $env:FLEX_HOME
  - cmd: dir %FLEX_HOME%

  - cmd: mxmlc -version
  - cmd: adt -version

#build:
build_script:
- cmd: appWindows\_build.bat

test: off

deploy_script:
- cmd: appveyor-to-gh-pages-branch.cmd
