version: 1.0.{build}

branches:
  only:
    - master

environment:
  GITHUB_TOKEN:
    secure: 9i6jrWpBi99QC1gYYQYMGIxyueGdDuTrbxKIkdwJJGjvv8nhiQeGk4V7lb1Wy6C4
  GITHUB_EMAIL:
    secure: 9KuPMPaDBiLnWjbCSsubN+MFp4a9LOyqPzWcN3zTecQ=
  SDK_REPO: flex-sdk
  SDK_TARGET: 4.15.0-AIR-22-minimal-Windows

install:
#  - ps: echo "install - $env:SDK_TARGET"
  - ps: echo 'install:' $env:SDK_TARGET
  - cmd: echo 'install:' %SDK_TARGET%
#  - ps: wget https://github.com/mojoco/$env:SDK_REPO/archive/$env:SDK_TARGET.zip -O $env:APPVEYOR_BUILD_FOLDER\$env:SDK_TARGET.zip
  - ps: curl https://github.com/mojoco/$env:SDK_REPO/archive/$env:SDK_TARGET.zip -o $env:APPVEYOR_BUILD_FOLDER\$env:SDK_TARGET.zip

cache:
  # invalidate whenever appveyor.yml is changed !
  # ?..
# - '%APPVEYOR_BUILD_FOLDER%\%SDK_TARGET%.zip -> appveyor.yml'
  - '%APPVEYOR_BUILD_FOLDER%\%SDK_TARGET%.zip'

before_build:
#  - ps: ls $env:APPVEYOR_BUILD_FOLDER
  - cmd: unzip %APPVEYOR_BUILD_FOLDER%\%SDK_TARGET%.zip
#  - ps: ls $env:APPVEYOR_BUILD_FOLDER
  - cmd: rename "%APPVEYOR_BUILD_FOLDER%\%SDK_REPO%-%SDK_TARGET%" "flex-sdk"
#  - ps: ls $env:APPVEYOR_BUILD_FOLDER
  - cmd: set FLEX_HOME=%APPVEYOR_BUILD_FOLDER%\flex-sdk
  - cmd: set PATH=%PATH%;%FLEX_HOME%\bin

build_script:
# - cmd: appWindows\_build.bat
  - cmd: mxmlc -version
  - cmd: adt -version

test: off

#deploy_script:
#- cmd: appveyor-to-gh-pages-branch.cmd
