version: 1.0.{build}

branches:
  only:
    - master

environment:
  GITHUB_TOKEN:
    secure: 9i6jrWpBi99QC1gYYQYMGIxyueGdDuTrbxKIkdwJJGjvv8nhiQeGk4V7lb1Wy6C4
  GITHUB_EMAIL:
    secure: 9KuPMPaDBiLnWjbCSsubN+MFp4a9LOyqPzWcN3zTecQ=
  SDK_REPO: flex-sdk
  SDK_TARGET: 4.15.0-AIR-22-minimal-Windows

  # debug !!!
  #APPVEYOR_CACHE_SKIP_RESTORE: true

install:
  - if not exist %APPVEYOR_BUILD_FOLDER%\sdk appveyor-install.cmd

cache:
  # on invalide le cache, a chaque changement du 'appveyor.yml' !
  - '%APPVEYOR_BUILD_FOLDER%\sdk -> appveyor.yml'

before_build:
#  - ps: ls $env:APPVEYOR_BUILD_FOLDER/sdk
#  - dir %APPVEYOR_BUILD_FOLDER%\sdk
  - set FLEX_HOME=%APPVEYOR_BUILD_FOLDER%\sdk\flex
  - set PATH=%PATH%;%FLEX_HOME%\bin
  - mxmlc -version
  - adt -version

build_script:
 - call %APPVEYOR_BUILD_FOLDER%\appWindows\_build.bat

test: off

#deploy_script:
#- cmd: appveyor-to-gh-pages-branch.cmd
