version: 1.0.{build}

branches:
  only:
    - master

environment:
  GITHUB_TOKEN:
    secure: 9i6jrWpBi99QC1gYYQYMGIxyueGdDuTrbxKIkdwJJGjvv8nhiQeGk4V7lb1Wy6C4
  GITHUB_EMAIL:
    secure: 9KuPMPaDBiLnWjbCSsubN+MFp4a9LOyqPzWcN3zTecQ=

install:
  - ps: echo "install.."
  - cmd: echo APPVEYOR_BUILD_FOLDER - %APPVEYOR_BUILD_FOLDER%
  - ps: echo "APPVEYOR_BUILD_FOLDER - $env:APPVEYOR_BUILD_FOLDER"
  - ps: wget https://github.com/mojoco/flex-sdk/archive/4.16.1-AIR-28-minimal-macOS.tar.gz -O $env:APPVEYOR_BUILD_FOLDER/flex-sdk.tar.gz
  - ps: ls $env:APPVEYOR_BUILD_FOLDER

cache:
#  - C:\ProgramData\chocolatey\lib -> appveyor.yml

build: off

test: off

deploy_script:
- cmd: appveyor-to-gh-pages-branch.cmd
