# If you have appveyor.yml in your repo
# it will override all settings made on the UI
# unless explicitly disabled by Ignore appveyor.yml.

# sample: https://www.appveyor.com/docs/appveyor-yml/

version: 1.0.{build}


#---------------------------------#
#       build configuration       #
#---------------------------------#

build_script:
- cmd: echo "Yop"
- cmd: dir    # C:\projects\test-travis-ci
- cmd: call app\_build.bat

after_build:
  - ps: echo $artifacts


#---------------------------------#
#       tests configuration       #
#---------------------------------#

test: off


#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:
  - path: app\Main.mxml
    name: mypackage

#---------------------------------#
#     deployment configuration    #
#---------------------------------#

deploy:

  # Deploy to GitHub Releases
- provider: GitHub
  auth_token:
    secure: 8w0eWM2T2k6+tdjoZ/PpgmMHjYCLDRNldleQQisztMFuzi4IBlQuVI0yr1MQa6RQ
  artifact: app\Main.mxml
#  artifact: mypackage
  draft: false
  prerelease: false
  repository: mojoco/test-travis-CI
  on:
    branch: master                # release from master branch only

# to run your custom scripts instead of provider deployments
#deploy_script:
#  - cmd: echo "deploy_script.."
# ..
