version: 1.0.{build}

branches:
  only:
    - master

environment:
  GITHUB_TOKEN:
    secure: 9i6jrWpBi99QC1gYYQYMGIxyueGdDuTrbxKIkdwJJGjvv8nhiQeGk4V7lb1Wy6C4
  GITHUB_EMAIL:
    secure: 9KuPMPaDBiLnWjbCSsubN+MFp4a9LOyqPzWcN3zTecQ=
  SDK_REPO: flex-sdk
  SDK_TARGET: 4.15.0-AIR-22-minimal-Windows

  # debug !!!
  APPVEYOR_CACHE_SKIP_RESTORE: true

install:
  - if not exist %APPVEYOR_BUILD_FOLDER%\sdk appveyor-install.cmd
  - set FLEX_HOME=%APPVEYOR_BUILD_FOLDER%\sdk\%SDK_REPO%-%SDK_TARGET%
  - set PATH=%PATH%;%FLEX_HOME%\bin

cache:
  # invalidate whenever appveyor.yml is changed !
  # on invalide le cache, a chaque changement du 'appveyor.yml' !
  # ?..
# - '%APPVEYOR_BUILD_FOLDER%\%SDK_TARGET%.zip -> appveyor.yml'
#  - '%APPVEYOR_BUILD_FOLDER%\%SDK_TARGET%.zip'
  - '%APPVEYOR_BUILD_FOLDER%\sdk'

before_build:
#  - ps: ls $env:APPVEYOR_BUILD_FOLDER
#  - dir %APPVEYOR_BUILD_FOLDER%

#  - cmd: unzip -n %APPVEYOR_BUILD_FOLDER%\%SDK_TARGET%.zip -d .
#  - cmd: rename "%APPVEYOR_BUILD_FOLDER%\%SDK_REPO%-%SDK_TARGET%" "flex-sdk"
#  - cmd: set FLEX_HOME=%APPVEYOR_BUILD_FOLDER%\flex-sdk
#  - cmd: set PATH=%PATH%;%FLEX_HOME%\bin

build_script:
# - cmd: appWindows\_build.bat
  - mxmlc -version
  - adt -version

test: off

#deploy_script:
#- cmd: appveyor-to-gh-pages-branch.cmd
