# If you have appveyor.yml in your repo
# it will override all settings made on the UI
# unless explicitly disabled by Ignore appveyor.yml.

# sample: https://www.appveyor.com/docs/appveyor-yml/

version: 1.0.{build}


#---------------------------------#
#       build configuration       #
#---------------------------------#

build_script:
- cmd: echo "Yop"
- cmd: dir    # C:\projects\test-travis-ci

after_build:
  - ps: echo $artifacts


#---------------------------------#
#       tests configuration       #
#---------------------------------#

test: off


#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:
  - path: .\app\Main.mxml


#---------------------------------#
#     deployment configuration    #
#---------------------------------#

deploy:

  # Deploy to GitHub Releases
- provider: GitHub
  auth_token:
    secure: EI/GlJ98+tWum+ZpKOQ6yxS2kkbzMpntSejKovxuvy77tDYC9aKOBxLCcDA8CzPWciR2KOGo/CW55SAFcZiSMFw7JceWt9lS3T904UB/h0Y=
  artifact: .\app\Main.mxml
  draft: false
  prerelease: false
  repository: mojoco/test-travis-CI
  on:
    branch: master                # release from master branch only

# to run your custom scripts instead of provider deployments
#deploy_script:
#  - cmd: echo "deploy_script.."
# ..
