version: 1.0.{build}

branches:
  only:
    - master

environment:
  GITHUB_TOKEN:
    secure: 9i6jrWpBi99QC1gYYQYMGIxyueGdDuTrbxKIkdwJJGjvv8nhiQeGk4V7lb1Wy6C4
  GITHUB_EMAIL:
    secure: 9KuPMPaDBiLnWjbCSsubN+MFp4a9LOyqPzWcN3zTecQ=
  SDK_REPO: flex-sdk
  SDK_TARGET: 4.15.0-AIR-22-minimal-Windows
  APPVEYOR_CACHE_SKIP_RESTORE: true

install:
  - appveyor-install.cmd

cache:
  # invalidate whenever appveyor.yml is changed !
  # ?..
# - '%APPVEYOR_BUILD_FOLDER%\%SDK_TARGET%.zip -> appveyor.yml'
  - '%APPVEYOR_BUILD_FOLDER%\%SDK_TARGET%.zip'

before_build:
#  - ps: ls $env:APPVEYOR_BUILD_FOLDER
  - dir %APPVEYOR_BUILD_FOLDER%

  - cmd: unzip -n %APPVEYOR_BUILD_FOLDER%\%SDK_TARGET%.zip
#  - ps: ls $env:APPVEYOR_BUILD_FOLDER
  - cmd: rename "%APPVEYOR_BUILD_FOLDER%\%SDK_REPO%-%SDK_TARGET%" "flex-sdk"
#  - ps: ls $env:APPVEYOR_BUILD_FOLDER
  - cmd: set FLEX_HOME=%APPVEYOR_BUILD_FOLDER%\flex-sdk
  - cmd: set PATH=%PATH%;%FLEX_HOME%\bin

build_script:
# - cmd: appWindows\_build.bat
  - cmd: mxmlc -version
  - adt -version

test: off

#deploy_script:
#- cmd: appveyor-to-gh-pages-branch.cmd
