os: osx

language: objective-c

branches:
  only:
  - master

before_script:
  - echo "before script.."

script:
  - echo "script.."

after_script:
  - echo "after script.."

before_deploy:
    - chmod +x ./travis-to-gh-pages-branch.sh

deploy:
  - provider: script
#   script: bash ./travis-to-gh-pages-branch.sh
    script: sh ./travis-to-gh-pages-branch.sh
#   script: chmod +x ./travis-to-gh-pages-branch.sh && sh ./travis-to-gh-pages-branch.sh
    on:
      branch: master
