os: osx

language: objective-c

branches:
  only:
    - master

cache:
  directories:
  
before_script:
  # set the JAVA_HOME which is not set by default for OSX Travis-CI workers
  - export "JAVA_HOME=`/usr/libexec/java_home`"
  - chmod +x app/_build.command
  - chmod +x app/_package.command

script:
  - cd app
  - ./_build.command
  - ./_package.command

before_deploy:
  # swf..
  - cp Main.swf $TRAVIS_BUILD_DIR/deploy/github-pages

  # zip..
  # ( -y   store symbolic links as the link instead of the referenced file )
  - zip -r -y Main.zip Main.app
  - cp Main.zip $TRAVIS_BUILD_DIR/deploy/github-pages

  # dmg.. (best compression)
  - hdiutil create -format UDZO -srcfolder Main.app Main.dmg
  - cp Main.dmg $TRAVIS_BUILD_DIR/deploy/github-pages

  - ls "$TRAVIS_BUILD_DIR/deploy/github-pages"

# ?..
  # prépare le déploiement ?..
  # cars le dossier 'target' disparait !!!
  # ===========================================================================
#  - mkdir $TRAVIS_BUILD_DIR/_BUILD
#  - cp -r $TRAVIS_BUILD_DIR/target/ $TRAVIS_BUILD_DIR/_BUILD

  

deploy:

    # if single-deploy, don't use '-' !
    #   provider: pages
    #
    # if multi-deploy, use list ('-') !
    #   - provider: pages
    #   - provider: releases
    #   - provider: etc..

  # on GitHub Pages..       ( https://docs.travis-ci.com/user/deployment/pages/ )
  # ===========================================================================
#  - provider: pages
  provider: pages
  skip-cleanup: true
  keep-history: true
  github-token: $GITHUB_TOKEN_02
  # local-dir: Directory to push to GitHub Pages, relative to the current directory, defaults to the current directory
  local-dir: deploy/github-pages
  on:
    branch: master

  # on GitHub Release..     ( https://docs.travis-ci.com/user/deployment/releases/ )
  # ===========================================================================
#  - provider: releases
#  api_key: $GITHUB_TOKEN_02
#  file:
#        - Main.dmg
#                       overwrite: true
#  skip_cleanup: true
#  on:
#    tags: true
#    branch: master

