os: osx

language: objective-c

branches:
  only:
  - master

install:
  - wget https://github.com/mojoco/flex-sdk/archive/4.16.1-AIR-28-minimal-macOS.tar.gz -O $TRAVIS_BUILD_DIR/flex-sdk.tar.gz
  - mkdir -p $TRAVIS_BUILD_DIR/flex-sdk
  - tar -xvf $TRAVIS_BUILD_DIR/flex-sdk.tar.gz --directory $TRAVIS_BUILD_DIR/flex-sdk --strip-components=1
  - export FLEX_HOME=$TRAVIS_BUILD_DIR/flex-sdk
  - export PATH=$PATH:$FLEX_HOME/bin/

cache:
  directories:
    - $TRAVIS_BUILD_DIR/flex-sdk

before_script:
  - echo "before script.."
  - mxmlc -version

script:
  - echo "script.."
  - cd appMacOS
# - chmod +x _build.command
  - sh ./_build.command

after_script:
  - echo "after script.."
  - sh ./travis-to-gh-pages-branch.sh
