language: objective-c

before_script:
  # set the JAVA_HOME which is not set by default for OSX Travis-CI workers
  - export "JAVA_HOME=`/usr/libexec/java_home`"
  # Download and install a specific Flash Player from the Adobe Archives:
  # http://helpx.adobe.com/flash-player/kb/archived-flash-player-versions.html
  - sh getFpFromArchive.sh 'http://download.macromedia.com/pub/flashplayer/installers/archive/fp_11.7.700.225_archive.zip'

script: mvn test -DflashPlayer.command=Flash\ Player\ Debugger.app/Contents/MacOS/Flash\ Player\ Debugger

before_deploy:
  - mkdir $TRAVIS_BUILD_DIR/_BUILD
#  - cp -r /Users/travis/build/mojoco/travis-CI-actionscript-demo/target/test-classes $TRAVIS_BUILD_DIR/_BUILD
  - cp -r $HOME/build/$TRAVIS_REPO_SLUG $TRAVIS_BUILD_DIR/_BUILD
  
  - echo "==========================================================================="
  - ls $TRAVIS_BUILD_DIR
  - echo "==========================================================================="
  - ls $HOME
#  - echo "==========================================================================="
#  - ls $HOME/build
#  - echo "==========================================================================="
#  - ls /Users/travis/build/mojoco/travis-CI-actionscript-demo
  - echo "==========================================================================="
  - ls $HOME/build/$TRAVIS_REPO_SLUG/target
  - echo "==========================================================================="
  - ls $HOME/build/$TRAVIS_REPO_SLUG/target/classes
  - echo "==========================================================================="
  - ls $HOME/build/$TRAVIS_REPO_SLUG/target/test-classes
#  - echo "==========================================================================="
#  - ls $HOME/build/$TRAVIS_REPO_SLUG/target/surefire-reports
  - echo "==========================================================================="

deploy:
  provider: pages
#  local-dir: $HOME/build/$TRAVIS_REPO_SLUG/target/test-classes
#  file:
#    - /Users/travis/build/mojoco/travis-CI-actionscript-demo/target/test-classes/TestRunner.swf
#    - $HOME/build/$TRAVIS_REPO_SLUG/target/travis-CI-actionscript-demo-1.0.0.swf
  skip-cleanup: true
  keep-history: true
  github-token: $GITHUB_API_TOKEN
  on:
    branch: master
