os: osx

language: objective-c

branches:
  only:
  - master

before_script:
  - echo "before script.."

script:
  - echo "script.."

after_script:
  - echo "after script.."

deploy:
  - provider: script
    skip-cleanup: true
    script: bash ./travis-to-gh-pages-branch.sh
    on:
      branch: master
