language: objective-c

before_script:
  # set the JAVA_HOME which is not set by default for OSX Travis-CI workers
  - export "JAVA_HOME=`/usr/libexec/java_home`"
  # Download and install a specific Flash Player from the Adobe Archives:
  # http://helpx.adobe.com/flash-player/kb/archived-flash-player-versions.html
  - sh getFpFromArchive.sh 'http://download.macromedia.com/pub/flashplayer/installers/archive/fp_11.7.700.225_archive.zip'

script: mvn test -DflashPlayer.command=Flash\ Player\ Debugger.app/Contents/MacOS/Flash\ Player\ Debugger

before_deploy:
  
  - echo "==========================================================================="
  - ls $TRAVIS_BUILD_DIR
#  - echo "==========================================================================="
#  - ls $HOME
  - echo "==========================================================================="
  - ls $TRAVIS_BUILD_DIR/target
#  - echo "==========================================================================="
#  - ls $HOME/build/$TRAVIS_REPO_SLUG/target/classes
#  - echo "==========================================================================="
#  - ls $HOME/build/$TRAVIS_REPO_SLUG/target/test-classes
  - echo "==========================================================================="
  
#  - cd app
#  - chmod +x _build.command
#  - ./_build.command

  - mkdir $TRAVIS_BUILD_DIR/_BUILD
  - cp -r $TRAVIS_BUILD_DIR/target/ $TRAVIS_BUILD_DIR/_BUILD


deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  github-token: $GITHUB_TOKEN_02
  on:
    branch: master
