language: objective-c

cache:
  directories:
  - .autoconf
  - $HOME/.m2
  
before_script:
  # set the JAVA_HOME which is not set by default for OSX Travis-CI workers
  - export "JAVA_HOME=`/usr/libexec/java_home`"
  # Download and install a specific Flash Player from the Adobe Archives:
  # http://helpx.adobe.com/flash-player/kb/archived-flash-player-versions.html
  - sh getFpFromArchive.sh 'http://download.macromedia.com/pub/flashplayer/installers/archive/fp_11.7.700.225_archive.zip'

script: mvn test -DflashPlayer.command=Flash\ Player\ Debugger.app/Contents/MacOS/Flash\ Player\ Debugger

before_deploy:
  
  - echo "==========================================================================="
  - ls $TRAVIS_BUILD_DIR
#  - echo "==========================================================================="
#  - ls $HOME
  - echo "==========================================================================="
  - ls $TRAVIS_BUILD_DIR/target
#  - echo "==========================================================================="
#  - ls $HOME/build/$TRAVIS_REPO_SLUG/target/classes
#  - echo "==========================================================================="
#  - ls $HOME/build/$TRAVIS_REPO_SLUG/target/test-classes

  - echo "==========================================================================="
#  - ls ~
#  - ls ~/.m2
#  - ls ~/.m2/repository
#  - ls ~/.m2/repository/net
#  - ls ~/.m2/repository/org/apache
#  - ls ~/.m2/repository/org/apache/apache
#  - ls ~/.m2/repository/org/apache/commons
#  - ls ~/.m2/repository/org/apache/maven
#  - ls ~/.m2/repository/org/sonatype
  
  - echo "==========================================================================="




# build, package..
# ===========================================================================
  - cd app
  
  - chmod +x _build.command
  - ./_build.command
  
  - chmod +x _package.command
  - ./_package.command

  # zip..
  # ( -y   store symbolic links as the link instead of the referenced file )
  - zip -r -y Main.zip Main.app

  # dmg.. (best compression)
  - hdiutil create -format UDZO -srcfolder Main.app Main.dmg
  - cp Main.dmg $TRAVIS_BUILD_DIR/deploy/github-pages
#===========================================================================



# ?..
# prépare le déploiement ?..
# cars le dossier 'target' disparait !!!
# ===========================================================================
  - mkdir $TRAVIS_BUILD_DIR/_BUILD
  - cp -r $TRAVIS_BUILD_DIR/target/ $TRAVIS_BUILD_DIR/_BUILD

  - mkdir $TRAVIS_BUILD_DIR/_BUILD/github-pages
  - cp $TRAVIS_BUILD_DIR/deploy/github-pages/README.md  $TRAVIS_BUILD_DIR/_BUILD/github-pages
  - cp Main.dmg                                         $TRAVIS_BUILD_DIR/_BUILD/github-pages
  
  
  

deploy:

  # on GitHub Pages..       ( https://docs.travis-ci.com/user/deployment/pages/ )
  # ===========================================================================
#  - provider: pages
  provider: pages
  skip-cleanup: true
  keep-history: true
  github-token: $GITHUB_TOKEN_02
# local-dir: $TRAVIS_BUILD_DIR/deploy/github-pages
  local-dir: $TRAVIS_BUILD_DIR/_BUILD/github-pages
  on:
    branch: master

  # on GitHub Release..     ( https://docs.travis-ci.com/user/deployment/releases/ )
  # ===========================================================================
#  - provider: releases
#  api_key: $GITHUB_TOKEN_02
#  file:
#        - Main.dmg
#                       overwrite: true
#  skip_cleanup: true
#  on:
#    tags: true
#    branch: master

