os: osx

language: objective-c

branches:
  only:
  - master

before_script:
  - echo "before script.."

script:
  - echo "script.."

after_script:
  - echo "after script.."
#  - chmod +x ./travis-to-gh-pages-branch.sh
  - sh ./travis-to-gh-pages-branch.sh
