os: osx

language: objective-c

branches:
  only:
  - master

before_script:
  - cd app
  - chmod +x _build.command
  - chmod +x _package.command

script:
  - ./_build.command
  - ./_package.command

after_script:
  - echo "after script.."

before_deploy:

  # zip..
  - zip -r -y Main.zip Main.app

  # dmg..
  - hdiutil create -format UDZO -srcfolder Main.app Main.dmg
  - cp Main.dmg $TRAVIS_BUILD_DIR/deploy/github-pages
  
  # swf..
  - cp Main.swf $TRAVIS_BUILD_DIR/deploy/github-pages
 
deploy:
  provider: script
    script: bash ./travis-to-gh-pages-branch.sh
    on:
      branch: master
  verbose: true
