version: 1.0.{build}

platform:
#- x86
- x64

branches:
  only:
    - master

skip_tags: true


#---------------------------------#
#       build configuration       #
#---------------------------------#

build_script:
- cmd: echo "Yop"
#- ps: java -version
- cmd: dir    # C:\projects\test-travis-ci
- cmd: call appWin\_build.bat
- cmd: cd C:\projects\test-travis-ci
- cmd: call appWin\_package.bat
- cmd: cd C:\projects\test-travis-ci
- cmd: dir appWin

after_build:
#  - ps: echo $artifacts
#  - cmd: dir appWin


#---------------------------------#
#       tests configuration       #
#---------------------------------#

test: off


#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:
  - path: appWin\Main.swf
    name: AppSwf
  - path: appWin\Main.exe
    name: AppExe
    type: File

#---------------------------------#
#     deployment configuration    #
#---------------------------------#

deploy:

  # Deploy to GitHub Releases
- provider: GitHub
  auth_token:
    secure: 9i6jrWpBi99QC1gYYQYMGIxyueGdDuTrbxKIkdwJJGjvv8nhiQeGk4V7lb1Wy6C4
#  artifact: appWin\Main.swf
  artifact: AppSwf, AppExe
  tag: release-test
  force_update: true
  draft: false
  prerelease: false
  repository: mojoco/test-travis-CI
  on:
    branch: master                # release from master branch only

# to run your custom scripts instead of provider deployments
#deploy_script:
#  - cmd: echo "deploy_script.."
# ..


# git subtree push --prefix dist origin gh-pages
